Resolve #9 - Add custom screenshot paths
perceptia/perceptia pull request #25
Opened 2017-06-16 08:12 UTC by ZOTTCE

2017-06-16 17:37 UTC, darkelement commented on perceptia/perceptiactl/perceptiactl.rs
> +                screenshot::process(now.format("%Y-%m-%d_%H%M%S").to_string());
This file name will not work. It has to have extension. Without it `image` crate fails to determine the format. What do you think about adding some prefix? "screenshot-%Y-%m-%d_%H%M%S.png" would be good.

2017-06-16 17:42 UTC, darkelement commented on perceptia/perceptiactl/screenshot.rs
> +            path,
Some distributions are not up to date and still use rustc 1.16 where field shorthands give an error.

2017-06-16 17:43 UTC, proton-decay requested changes
Thank you! Two small corrections and this commit will be perfect.

2017-06-18 12:55 UTC, ZOTTCE commented
Oh, sorry, forgot about an extension. It seems good now.

2017-06-18 15:54 UTC, proton-decay approved these changes

2017-06-18 15:55 UTC, merged

2017-06-18 16:00 UTC, darkelement commented
Now it works perfectly. Do you maybe plan to stay longer with perceptia? If so, do you see other interesting issues you would like to solve or should I find another ones? Do you have comments about perceptia?

2017-06-18 16:25 UTC, ZOTTCE commented
I need to understand how perceptia works before I can start to do something.

2017-06-18 16:33 UTC, darkelement commented
Small issues are great for learning.

Here's general overview of architecture: https://github.com/perceptia/perceptia/wiki/Architecture

If something is not obvious by reading the code (and that's probably the case in many places) - this is a bug. Open an issue and I will add more comments or documentation.

Soon there will be support for offscreen test mode with VNC so it will be easier to develop perceptia without second computer.